### ISSUE TITLE
建议放弃simplejson，该货性能不行，改用gjson

### ISSUE THREAD

**Issue by IIInsomnia** [PingPlusPlus/pingpp-go#10]

**Comment by samurai00** [comment]
我们没有用 simplejson 就是直接用的 'encoding/json'。你说的 gjson 如果是 https://github.com/tidwall/gjson 的话，不符合我们的需求，这个 gjson 主要提供的是 从 字符串 直接获取 值，而我们需要整体转换映射。

**Comment by IIInsomnia** [comment]
明白了
