### ISSUE TITLE
出现大bug

### ISSUE THREAD

**Issue by IIInsomnia** [PingPlusPlus/pingpp-go#11]
charge.New()

返回 error：

http: ContentLength=355 with Body length 0

**Comment by go-wyvern** [comment]
您好，为方便我们定位问题，请把问题描述得更详细一些。比如是否必现，请求的渠道等，如有必要，可以联系我们CS，提供您的app_id，帮助我们更快定位问题

**Comment by samurai00** [comment]
fixed
