### ISSUE TITLE
走点心吧，兄弟

### ISSUE THREAD

**Issue by Mint-Zhao-Chiu** [PingPlusPlus/pingpp-go#5]
notify里面，你用了samplejson就引入库嘛，没有好的ide，我推荐你用idea。或者测试好了再传上来

**Comment by lumixiliu** [comment]
谢谢你的建议。
notify.go 中引入的 simplejson 需要你先： go get github.com/bitly/go-simplejson。要不然编译会报错。

--------------------------补充点--------------------------
notify.go 文件里面引用了 simplejson 库的，notifyDemo.go 里面还提供了调用示例。你直接运行 notifyDemo.go 或者更改 notifyDemo.go 文件中绑定的端口运行，然后往监听的地址 post 数据即可。因为 notifyDemo.go 调用了 notify.go，而 simplejson 是在 notify.go 中调用，所以这里不需要再次引入 simplejson。你说的未引入，是否你并没有 go get github.com/bitly/go-simplejson，这样编译时是会报错的。还麻烦你再检查一下。
