### ISSUE TITLE
超级大bug，一直没有修改

### ISSUE THREAD

**Issue by mintzhao** [PingPlusPlus/pingpp-go#9]
函数 NewRequest(method, path, key, contentType string, body io.Reader, params []byte) (*http.Request, error) 中的key 参数，既然用的是全局的Key， 何必这里要传一个key进来。。。。

请修改为 参数key，因为调用的时候可能不会用到全局Key，我们自定义的 ChargeClient， 而不是用的 getC（）获取的client

**Comment by guangguang** [comment]
谢谢，已经修改
